
services:
    
    sonata.admin.manager.splash:
        class: App\ExplorerBundle\Model\ObjectsManager
        arguments: [ '@doctrine' ]
        public: true

    sonata.admin.manager.splash_form:
        class: App\ExplorerBundle\Model\ObjectsManager


    splash.explorer.twig.extension:
        class: App\ExplorerBundle\Twig\ExplorerExtension
        tags:   ["twig.extension"]
