
services:
    
    sonata.admin.manager.splash:
        class: App\ExplorerBundle\Model\ObjectsManager
        arguments: [ '@splash.connectors.manager', "@doctrine.orm.entity_manager" ]
        public: true

    splash.explorer.twig.extension:
        class: App\ExplorerBundle\Twig\ExplorerExtension
        tags:   ["twig.extension"]
