# FriendsOfSymfony Bundles Configurations

fos_user:
    db_driver:              orm 
    firewall_name:          main
    user_class:             App\UserBundle\Entity\User
    
    
    from_email:     
        address:            noreply@splashsync.com
        sender_name:        SplashSync
        
    group:
        group_class:        App\UserBundle\Entity\Group
        group_manager:      sonata.user.orm.group_manager                   

    service:
        user_manager:       sonata.user.orm.user_manager                      
        
        