
splash_faker:
    
    objects:    
        - { id: "short",    name: "Fake Short Object",  format: "short" }
        - { id: "simple",   name: "Fake Simple Object", format: "simple" }
        - { id: "list",     name: "Fake List Object",   format: "list" }
        - { id: "image",    name: "Fake Image Object",  format: "image" }



