
splash:
#    cache: 
#        enabled: false
#        lifetime: 10
    
    connections:
        


                
        node2:
            id:                 b85448f1741e394e
            key:                NWMwNmQyNTdiOGI0YTUuMjc2Nzk4NzI1YzA2ZDI1N2I4Y2M3Ni         
            name:               Soap to Faker
            host:               false
            connector:          soap
            config:     
                Extended:           true
                WsIdentifier:       fd13e99c10a03840
                WsEncryptionKey:    NWMyMzY1MWRiYjVhMzcuNDgxMjQwNjg1YzIzNjUxZGJiNzI4MS                
                WsHost:             http://localhost
                WsPath:             /SplashToolkit/public/ws/splash
#                WsHost:             http://localhost
#                WsPath:             /SplashToolkit/public/ws/webservice

        node1:
            id:                 fd13e99c10a03840
            key:                NWMyMzY1MWRiYjVhMzcuNDgxMjQwNjg1YzIzNjUxZGJiNzI4MS
            name:               Standalone
#            host:               false
#            host:               http://dev.splashsync.local/ws/soap
            host:               http://localhost/SplashToolkit/public/ws/soap            
            config:             
                param1:       true
                param2:       false
                
        mailchimp:
            id:                 123456789
            key:                123456789WRiYjVhMzcuNDgxMjQwNjg1YzIzNjUxZGJiNzI4MS
            name:               MailChimp
            host:               false
            connector:          mailchimp

        mailjet:
            id:                 987456321
            key:                123456789WRiYjVhMzcuNDgxMjQwNjg1YzIzNjUxZGJiNzI4MS
            name:               MailJet
            host:               false
            connector:          mailjet
                
        sendinblue:
            id:                 33669988
            key:                123456789WRiYjVhMzcuNDgxMjQwNjg1YzIzNjUxZGJiNzI4MS
            name:               SendInBlue
            host:               false
            connector:          sendinblue

#        node3:
#            id:                 987654321
#            key:                12345678901234567890174171171
#            name:               Soap to Soap
#            host:               http://localhost/SplashToolkit/public/ws/soap
#            connector:          soap
#            config:     
#                Extended:           true
#                WsIdentifier:       12345678
#                WsEncryptionKey:    12345678901234567890174171171                
#                WsHost:             http://localhost
#                WsPath:             /SplashToolkit/public/ws/soap
#                
        wp:
            id:                 76b59760e4acdb68
            key:                NWE3MmVkMzFmMTdiMDcuNTI3NDgyNTE1YTcyZWQzMWYxOTM3NC
            name:               Soap to Wp
            host:               false
#            host:               http://dev.splashsync.local/ws/soap            
#            host:               http://localhost/SplashToolkit/public/ws/soap
            connector:          soap
            config:             
                Extended:           true
                WsIdentifier:       76b59760e4acdb68
                WsEncryptionKey:    NWE3MmVkMzFmMTdiMDcuNTI3NDgyNTE1YTcyZWQzMWYxOTM3NC                
#                WsHost:             http://localhost
#                WsPath:             /Wordpress/Wp-4.9/wp-content/plugins/splash-connector/vendor/splash/phpcore/soap.php            
#                
#        dol:
#            id:                 aa293d4e85e22cae
#            key:                NWE5NTdkOTc5Y2QyYzYuMTI5NzI2NTg1YTk1N2Q5NzljZWFiNy
#            name:               Soap to Dolibarr
##            host:               false
#            host:               http://localhost/SplashToolkit/public/ws/soap
#            connector:          soap
#            config:             
#                Extended:           true
#                WsIdentifier:       aa293d4e85e22cae
#                WsEncryptionKey:    NWE5NTdkOTc5Y2QyYzYuMTI5NzI2NTg1YTk1N2Q5NzljZWFiNy                
#                WsHost:             http://localhost
#                WsPath:             /Dolibarr/Dol-7.0/custom/splash/vendor/splash/phpcore/soap.php                   