
splash:
    connections:
        
        node1:
            id:                 ff8b964bb4b53ae7
            key:                NWJjM2MzMDRkODg4MTkuMTUxNTg3MDk1YmMzYzMwNGQ4OWZlNi
            name:               Standalone
#            host:               false
            host:               http://dev.splashsync.local/ws/soap
            config:             
                param1:       true
                param2:       false

                
        node2:
            id:                 12345678
            key:                12345678901234567890174171171
            name:               Serveur 2
            host:               false
            config:             
                param1:       true
                param2:       false                
                
                