
splash:
    connections:
        
        standalone:
            id:                 12345678
            key:                12345678901234567890
            config:             
                param1:       true
                param2:       false
                
                
                