################################################################################
#
#  This file is part of SplashSync Project.
#
#  Copyright (C) Splash Sync <www.splashsync.com>
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
#  For the full copyright and license information, please view the LICENSE
#  file that was distributed with this source code.
#
#  @author Bernard Paquier <contact@splashsync.com>
#
################################################################################

################################################################
# Set any variables we need
variables:
  COMPOSER_MEMORY_LIMIT:  -1

################################################################
# Defined Pipeline Stages
stages:
  - tests
  - deploy

################################################################
# Functional Tests
################################################################
tests:
#    when:       manual
    image:      registry.gitlab.com/badpixxel-projects/php-sdk:php-8.0
    stage:      tests
    tags:       ['Dedicated']
    retry:      2
    ################################################################################
    # Run Test Script
    script:
      ################################################################
      # Setup Travis
      - curl -s https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/ci/configure.sh  | sh
      # Deploy Symfony Files
      - curl -s https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/symfony/deploy.sh | sh
      # Setup Symfony Version & Create Database
      - curl -s https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/symfony/configure.sh | sh
      # Install Symfony
      - curl -s https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/symfony/install.sh | sh
      ################################################################
      # Execute Code Quality Analyze
      - curl -s https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/ci/grumphp.sh | sh
    ################################################################################
    # Run After Script
    after_script:
      - curl -s https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/ci/after.sh | sh

#################################################################
## Build Documentation
#################################################################
pages:
#    when:       manual
    image:      registry.gitlab.com/splashsync/php-console:pages
    stage:      deploy
    tags:       ['Dedicated']
    retry:      2
    services:
        - docker:dind
    ################################################################################
    # Run Test Script
    script:
        # Deploy Symfony Files
        - curl -s https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/symfony/deploy.sh | sh
        # Run Composer to Build deps
        - curl -s https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/ci/composer.sh  | bash
        # Build Documentation
        - php vendor/bin/grumphp run --tasks=build-docs
    artifacts:
        paths:
          - public

################################################################
# Build Docker Images for Testing
################################################################
docker:
#    when:       manual
    stage:      deploy
    image:      docker:stable
    tags:       ['Dedicated-Docker']
    services:
        - docker:dind
    before_script:
        - docker info
    script:
        - echo "Build & Upload Docker Image"
        # Build & Upload Splash All Docker Images
        - docker build -t splashsync/toolkit:1.0 docker
        # Connect Docker to DockerHub
        - docker login -u splashsync -p $DOCKER_HUB_TOKEN
        - docker push splashsync/toolkit:1.0
    except:
        - schedules
