################################################################################
#
#  This file is part of SplashSync Project.
#
#  Copyright (C) Splash Sync <www.splashsync.com>
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
#  For the full copyright and license information, please view the LICENSE
#  file that was distributed with this source code.
#
#  @author Bernard Paquier <contact@splashsync.com>
#
################################################################################

################################################################
# Set any variables we need
variables:
  COMPOSER_MEMORY_LIMIT:  -1

################################################################
# Defined Pipeline Stages
stages:
  - tests
  - deploy

################################################################
# Functional Tests
################################################################
tests:
    image: registry.gitlab.com/badpixxel-projects/php-sdk:php-7.3
    stage:      tests
    tags:       ['Dedicated']
    retry:      2
    ################################################################################
    # Run Test Script
    script:
      ################################################################
      # Setup Travis
      - curl -s https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/ci/configure.sh  | sh
      # Deploy Symfony Files
      - curl -s https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/symfony/deploy.sh | sh
      # Setup Symfony Version & Create Database
      - curl -s https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/symfony/configure.sh | sh
      # Install Symfony
      - curl -s https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/symfony/install.sh | sh
      ################################################################
      # Execute Code Quality Analyze
      - curl -s https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/ci/grumphp.sh | sh
    ################################################################################
    # Run After Script
    after_script:
      - curl -s https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/ci/after.sh | sh

#################################################################
## Build Documentation
#################################################################
pages:
  image:      registry.gitlab.com/splashsync/php-console:pages
  stage:      deploy
  tags:       ['Dedicated']
  retry:      2
  services:
    - docker:dind
  ################################################################################
  # Run Test Script
  script:
    # Run Composer to Build deps
    - curl -s https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/ci/composer.sh  | bash
    - rm -Rf public
    # Build Documentation
    - php splash/vendor/bin/grumphp run --tasks=build-docs
  artifacts:
    paths:
      - public
