################################################################################
#
#  This file is part of SplashSync Project.
# 
#  Copyright (C) Splash Sync <www.splashsync.com>
# 
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# 
#  For the full copyright and license information, please view the LICENSE
#  file that was distributed with this source code.
# 
#  @author Bernard Paquier <contact@splashsync.com>
#
################################################################################

################################################################################
# Docker Compose File
#
# This Docker File intend to Create a Complete Toolkit Environment
# for Development of Splash Modules
#
# 172.169.0.10        toolkit.splashsync.local
#
################################################################################

version: '3.4'

services:
    
    ################################################################################
    # Php Alpine Server Container
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        container_name: toolkit
        volumes:
            # Use Local Sources
            - ./config:/app/config
            - ./src:/app/src
            # - /mnt/data/WebDesign/GitHub/Splash/Php-SonataAdminSplashBundle:/app/vendor/splash/sonata-admin-splash-bundle:ro
            # Specify Local Configuration File
            - ./docker/config/splash.yaml:/app/config/packages/splash.yaml:ro
        hostname: toolkit.splashsync.local
        networks:
            toolkit:        { ipv4_address: 172.169.0.10 }
            splashsync:     { aliases: [ toolkit.splashsync.local ] }

networks:
    ################################################################################
    # Default Private Network
    toolkit:
        driver: bridge
        ipam:
            config:
                - subnet: 172.169.0.0/24
    ################################################################################
    # External Splash Network
    splashsync:
        external: true
