################################################################################
#
#  This file is part of SplashSync Project.
# 
#  Copyright (C) Splash Sync <www.splashsync.com>
# 
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# 
#  For the full copyright and license information, please view the LICENSE
#  file that was distributed with this source code.
# 
#  @author Bernard Paquier <contact@splashsync.com>
#
################################################################################

################################################################################
# Docker Compose File
#
# This Docker File intend to Create a Complete Toolkit Envirenement 
# for Developpement of Splash Modules
#
# To us different PS Version coinfigured, you need to add hosts to /etc/hosts
# 
# 172.169.0.10        toolkit.splashsync.local
#
################################################################################


version: '3.4'

services:
    ################################################################################
    # MySql Container    
    mysql:
        image: 'mysql:5.7'
        container_name: toolkit_mysql
        environment:
            MYSQL_ROOT_PASSWORD:    'root'
            MYSQL_USER:             'symfony'
            MYSQL_PASSWORD:         'symfony'
            MYSQL_DATABASE:         'symfony'
        networks:
          - 'toolkit'
          
    ################################################################################
    # Pḧp Fpm Server Container   
    symfony:
        build:
            context: ./docker
            dockerfile: Dockerfile
        container_name: toolkit_symfony
        environment:
            COMPOSER_MEMORY_LIMIT: -1
            COMPOSER_HOME: '/home/docker/.composer' 
#        depends_on:
#            - mysql
        volumes:
            # Volume for Local Storage of Parameters           
#            - { name: app, type: volume, target: /app }
            # Read Only Src
            - './:/src:ro'
            - './bin:/app/bin:ro'
            - './config:/app/config'
#            - './config/bundles.php:/app/config/bundles.php'
            - './src:/app/src:ro'
            - './templates:/app/templates:ro'
            - './public:/app/public'
            - './docker/.env:/app/.env:ro'
            - './composer.json:/app/composer.json'
            # Shared Composer Cache
            - ~/.composer:/home/docker/.composer
#        working_dir: '/srv/pim'

#        ports:
#          - '8000:8000'
        hostname: toolkit.splashsync.local
        networks:
            toolkit:        { ipv4_address: 172.169.0.10 }
            splashsync:     { aliases: [ toolkit.splashsync.local ] }

networks:
    ################################################################################
    # Default Private Network
    toolkit:
        driver: bridge
        ipam:
            config:
                - subnet: 172.169.0.0/24
    ################################################################################
    # External Splash Network
    splashsync:
        external: true