
splash:

  ################################################################################
  # Configure Splash Bundle Parameters Cache
  # Cache is Enabled by Default to Store Custom Connectors Configuration
  # If disabled, configuration must be store in Static, on connection section
  ################################################################################
  #    cache:
  #        enabled: false
  #        lifetime: 10

  # Allow Notifications for Generic Users
  notify: ["ROLE_USER"]

  ################################################################################
  # List of Available Connector Connections
  ################################################################################

  connections:

    ########################################################################
    # Generic Soap Connection (Test & Debug your Generic Splash Servers)
    generic:
      id:                 ThisIsSplashWsId
      key:                ThisIsYourEncryptionKeyForSplash
      name:               My Generic Server
      host:               false
      connector:          soap
      config:
        WsIdentifier:       e4c179eb3cf2c4f9
        WsEncryptionKey:    NjQ2YzgzMzA1NWIyYjMuNzM2ODIwNzk2NDZjODMzMDU1Y2NiMy
        WsHost:             https://www.dealproffsen.no
        WsPath:             /splash-endpoint.php
        Extended:           true

    ########################################################################
    # Flat Local File Connector
    flat-local:
      id:                 ThisIsFlatLocalWsId
      key:                ThisIsNotASecretKeyForFlatLocal
      name:               Serveur 1 (Flat Local)
      connector:          flat
      config:
        Objects:
          Basic:
            targets:
              file:///app/vendor/splash/flat/src/Resources/samples/Basic/basic.json: auto
            model:  Splash\Connectors\Flat\OpenApi\Models\Samples\Basic
            ttl:    "-1 hour"


    ########################################################################
    # Dolibarr V16
    pres:
      id:                 972fa3ac4fd81c53
      key:                NjNhMWMzOTc1YmVmNjIuODgwMjM3Njk2M2ExYzM5NzVjMDgxNi
      name:               Pres de chez vous
      host:               false
      connector:          soap
      config:
        Extended:           true
        WsIdentifier:       972fa3ac4fd81c53
        WsEncryptionKey:    NjNhMWMzOTc1YmVmNjIuODgwMjM3Njk2M2ExYzM5NzVjMDgxNi
        WsHost:             https://dolibarr.predechezvouscircuitcourt.com/
        WsPath:             /custom/splash/vendor/splash/phpcore/soap.php

    ########################################################################
    # Dolibarr V16
    dol-16:
        id:                 ThisIsDol16Key
        key:                ThisTokenIsNotSoSecretChangeIt
        name:               Dolibarr 16
        host:               false
        connector:          soap
        config:
            Extended:           true
            WsIdentifier:       ThisIsDol16Key
            WsEncryptionKey:    ThisTokenIsNotSoSecretChangeIt
            WsHost:             http://v16.dolibarr.local
            WsPath:             /custom/splash/vendor/splash/phpcore/soap.php

    ps-8-0:
        id:                 ThisIsPs80Key
        key:                ThisTokenIsNotSoSecretChangeIt
        name:               Prestashop 8.0
        host:               false
        connector:          soap
        config:
            Extended:           true
            WsIdentifier:       ThisIsPs80Key
            WsEncryptionKey:    ThisTokenIsNotSoSecretChangeIt
            WsHost:             http://ps8-0.prestashop.local
            WsPath:             /modules/splashsync/vendor/splash/phpcore/soap.php