
splash:

  ################################################################################
  # Configure Splash Bundle Parameters Cache
  # Cache is Enabled by Default to Store Custom Connectors Configuration
  # If disabled, configuration must be store in Static, on connection section
  ################################################################################
  #    cache:
  #        enabled: false
  #        lifetime: 10

  # Allow Notifications for Generic Users
  notify: ["ROLE_USER"]

  ################################################################################
  # List of Available Connector Connections
  ################################################################################

  connections:

    ########################################################################
    # Generic Soap Connection (Test & Debug your Generic Splash Servers)
    generic:
      id:                 ThisIsSplashWsId
      key:                ThisIsYourEncryptionKeyForSplash
      name:               My Generic Server
      host:               false
      connector:          soap
      config:
        WsIdentifier:       ThisIsSplashWsId
        WsEncryptionKey:    ThisIsYourEncryptionKeyForSplash
        WsHost:             http://localhost
        WsPath:             /local/path/to/your/application/vendor/splash/phpcore/soap.php