parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    env(APP_SECRET): 'HXAE37X4DWTprvyLb10F3f7StmRStcZy'
    env(MAILER_DSN): 'null://localhost'

framework:
    secret:             '%env(APP_SECRET)%'
    form:               ~
    property_access:    ~
    assets:             ~
    annotations:        ~
    default_locale:     '%locale%'
    translator:
        default_path:   '%kernel.project_dir%/translations'
        fallbacks:
            - '%locale%'
    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: ~
    router:
        strict_requirements: true
    mailer:
        dsn:            '%env(MAILER_DSN)%'