# Sonata Admin        
sonata_admin:
    title:      Splash Toolkit
    title_logo: bundles/toolkit/img/Splash-Logo_Ico.png
    search:     false
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: center }
    options:
    security:
        role_admin:                     ROLE_USER

    assets:
        extra_stylesheets:
            # Sonata Admin BadPixxel Widgets Integration
            - bundles/splashadmin/js/admin.css
        extra_javascripts:
            # Sonata Admin BadPixxel Widgets Integration
            - bundles/splashadmin/js/admin.js

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
