services:

    ########################################################################
    # Splash Faker Standalone Events Listner
    splash.connector.faker.events:
        class: Splash\Connectors\FakerBundle\EventSubscriber\FakerEventsSuscriber
        arguments:  ["@=service('service_container').getParameter('splash_faker')"]
        tags:       ["kernel.event_subscriber"]


    ########################################################################
    # Splash Faker Field Buidler
    Splash\Connectors\FakerBundle\Services\FieldsBuilder:
        class: Splash\Connectors\FakerBundle\Services\FieldsBuilder
 
