services:

    ########################################################################
    # Splash Faker Standalone Objects
    splash.connector.faker.object.base:
        class: Splash\Connectors\FakerBundle\Objects\Generic
        arguments:  []
#        tags:       {""}


#    ########################################################################
#    # Node Faker Test Service
#    splash.nodes.faker.test.service:
#        class: Nodes\FakerBundle\Services\FakerService
#        arguments: ["@doctrine.orm.entity_manager", "@user.document_manager", "@service_container", "@=service('OpenObjectManager').getFormaterService()"]   
#
#    ########################################################################
#    # Node Faker FieldBuilder Service
#    splash.nodes.faker.fields.builder:
#        class: Nodes\FakerBundle\Services\FieldsBuilderService
#        arguments: []   
  
